version: "3.9"

services:
  all:
    build:
      context: .
      args:
        python_binary: python3
    volumes:
      - ./conf/opt/graphite/conf:/opt/graphite/conf
    ports:
      - "3000:3000"
      - "4000:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
